/**
 * Copyright (C), 2023,  .
 *
 * @file    ps3lib_cfg.h
 * @date    2023.06.25
 * @brief   配置相关数据结构与接口
 */
#ifndef __PS3LIB_CFG_H__
#define __PS3LIB_CFG_H__

#if defined(__cplusplus)
extern "C" {
#endif

/**
 * @brief  片外管理配置字段枚举 用于lib库使用 下发给固件前转换为固件配置字段枚举
 */
typedef enum Ps3LibCfgKeyEnum {
    PS3LIB_CFG_KEY_BASE = 0,
    PS3LIB_CFG_KEY_OCR,
    PS3LIB_CFG_KEY_NCQ,
    PS3LIB_CFG_KEY_SOFT_CHANNEL,
    PS3LIB_CFG_KEY_SOFT_CHAN_NUM,
    PS3LIB_CFG_KEY_SOFT_CHAN_GRP_CFG,
    PS3LIB_CFG_KEY_PASSTHROUGH,
    PS3LIB_CFG_KEY_JBOD,
    PS3LIB_CFG_KEY_DPM,
    PS3LIB_CFG_KEY_AUTOLOG_OUTPUT,
    PS3LIB_CFG_KEY_ALARM,
    PS3LIB_CFG_KEY_DEF_PD_CACHE,
    PS3LIB_CFG_KEY_PR_MODE,
    PS3LIB_CFG_KEY_PR_MAX_PD_CNT,
    PS3LIB_CFG_KEY_PR_INCLUDE_SSD,
    PS3LIB_CFG_KEY_PR_NUM_ITERATION,
    PS3LIB_CFG_KEY_PR_UCFG_AREAS,
    PS3LIB_CFG_KEY_PR_STARTTIME,
    PS3LIB_CFG_KEY_PR_DELAY,
    PS3LIB_CFG_KEY_PR_CORR_UCFG_AREAS,
    PS3LIB_CFG_KEY_CC_MODE,
    PS3LIB_CFG_KEY_CC_NUM_ITERATION,
    PS3LIB_CFG_KEY_CC_NUM_VD_DONE,
    PS3LIB_CFG_KEY_CC_STARTTIME,
    PS3LIB_CFG_KEY_CC_DELAY,
    PS3LIB_CFG_KEY_CC_EXCLUDEVD,
    PS3LIB_CFG_KEY_BACKPLANE_EXPOSE,
    PS3LIB_CFG_KEY_BACKPLANE_MODE,
    PS3LIB_CFG_KEY_CC_RATE,
    PS3LIB_CFG_KEY_REBUILD_RATE,
    PS3LIB_CFG_KEY_BGI_RATE,
    PS3LIB_CFG_KEY_PR_RATE,
    PS3LIB_CFG_KEY_MIGRATE_RATE,
    PS3LIB_CFG_KEY_TERMLOG,
    PS3LIB_CFG_KEY_TERMLOG_OPTION,
    PS3LIB_CFG_KEY_MOVEBACK,
    PS3LIB_CFG_KEY_CC_STATE,
    PS3LIB_CFG_KEY_PS_SPIN_DOWN_READY,
    PS3LIB_CFG_KEY_PS_SPIN_DOWN_HS,
    PS3LIB_CFG_KEY_PS_SPIN_DOWN_TIME,
    PS3LIB_CFG_KEY_PCI_BUS_NUM,
    PS3LIB_CFG_KEY_ABORT_CC_ON_ERR,
    PS3LIB_CFG_KEY_AUTO_REBUILD,
    PS3LIB_CFG_KEY_BATTERY_WARNING,
    PS3LIB_CFG_KEY_BOOT_DRIVE,
    PS3LIB_CFG_KEY_CACHE_BY_PASS,
    PS3LIB_CFG_KEY_FOREIGN_AUTO_IMPORT,
    PS3LIB_CFG_KEY_UNMAP,
    PS3LIB_CFG_KEY_SPIN_UP_DRV_CNT,
    PS3LIB_CFG_KEY_CACHE_FLUSH_INT,
    PS3LIB_CFG_KEY_SPIN_UP_DELAY,
    PS3LIB_CFG_KEY_ECC_BUCKET_SIZE,
    PS3LIB_CFG_KEY_ECC_BUCKET_LEAK_RATE,
    PS3LIB_CFG_KEY_COERCION,
    PS3LIB_CFG_KEY_EGHS_EUG,
    PS3LIB_CFG_KEY_EGHS_GHS,
    PS3LIB_CFG_KEY_PD_PREFAIL_SWITCH,
    PS3LIB_CFG_KEY_PDM,
    PS3LIB_CFG_KEY_PD_PREFAIL_INT,
    PS3LIB_CFG_KEY_PDM_TIMER_INT,
    PS3LIB_CFG_KEY_PDM_SUPPORT_READY,
    PS3LIB_CFG_KEY_BIOS_STATE,
    PS3LIB_CFG_KEY_BIOS_ABS,
    PS3LIB_CFG_KEY_BIOS_MAX_DEV_NUM,
    PS3LIB_CFG_KEY_CHANNEL_NUM,
    PS3LIB_CFG_KEY_AUTO_CONFIG,
    PS3LIB_CFG_KEY_PERF_MODE,
    PS3LIB_CFG_KEY_PI_STATE,
    PS3LIB_CFG_KEY_PERSONALITY,
    PS3LIB_CFG_KEY_SAFEID,
    PS3LIB_CFG_KEY_BOOT_WITH_PINNED_CACHE,
    PS3LIB_CFG_KEY_SGPIO_FORCE,
    PS3LIB_CFG_KEY_DIRECT_PD_MAPPING,
    PS3LIB_CFG_KEY_LARGE_IO_SUPPORT,
    PS3LIB_CFG_KEY_LARGE_QD,
    PS3LIB_CFG_KEY_LOAD_BALANCE_MODE,
    PS3LIB_CFG_KEY_MAINTAIN_PD_FAIL_HISTORY,
    PS3LIB_CFG_KEY_RESTORE_HOT_SPARE,
    PS3LIB_CFG_KEY_SES_MONITOR,
    PS3LIB_CFG_KEY_SES_MULTIPATH_CFG,
    PS3LIB_CFG_KEY_ACTIVITY_FOR_LOCATE,
    PS3LIB_CFG_KEY_FLUSH_WRITE_VERIFY,
    PS3LIB_CFG_KEY_CFG_AUTO_BALANCE,
    PS3LIB_CFG_KEY_DRIVE_ACTIVITY_LED,
    PS3LIB_CFG_KEY_LD_LIMIT,
    PS3LIB_CFG_KEY_LIMIT_MAX_RATE_SATA,
    PS3LIB_CFG_KEY_IMMEDIATE_IO,
    PS3LIB_CFG_KEY_USE_FDE_ONLY_ENCRYPT,
    PS3LIB_CFG_KEY_HDD_THERMAL_POLL_INT,
    PS3LIB_CFG_KEY_SDD_THERMAL_POLL_INT,
    PS3LIB_CFG_KEY_JBOD_WRITE_CACHE,
    PS3LIB_CFG_KEY_TRACE_NUM,
    PS3LIB_CFG_KEY_ASSEMBLY_NUM,
    PS3LIB_CFG_KEY_SAS_ADDR,
    PS3LIB_CFG_KEY_PD_FAIL_EVENT_OPTIONS,
    PS3LIB_CFG_KEY_MAINTENANCE,
    PS3LIB_CFG_KEY_PROFILE_ID,
    PS3LIB_CFG_KEY_PERF_MODE_VALUE,
    PS3LIB_CFG_KEY_DEV_ORDER_BY_FW,
    PS3LIB_CFG_KEY_OPS_SUPP_REBUILD_RATE,
    PS3LIB_CFG_KEY_AUTOCONFIG_SESMGMT,
    PS3LIB_CFG_KEY_AUTOCONFIG_SECURESED,
    PS3LIB_CFG_KEY_AUTOCONFIG_MULTIPATH,
    PS3LIB_CFG_KEY_AUTOCONFIG_MULTIINIT,
    PS3LIB_CFG_KEY_HII_VERSION,
    PS3LIB_CFG_KEY_STOP_ON_ERR,
    PS3LIB_CFG_KEY_DEFAULTS_REBUILD_RATE,
    PS3LIB_CFG_KEY_DEFAULTS_CACHE_FLUSH_INT,
    PS3LIB_CFG_KEY_NR,
} Ps3LibCfgKeyEnum_e;

/**
 * @brief   查询控制卡属性
 * @param[in]   ctrlId: 控制卡标识符
 * @param[in]   mglKey: 配置项枚举
 * @param[in]   len: 查询的配置项长度
 * @param[out]  pValue: 查询的value
 * @return  PS3_ERRNO_SUCCESS: 成功, 其他: 失败
 */
Ps3Errno ps3libCtrlSingleCfgGet(CtrlId_t ctrlId, Ps3LibCfgKeyEnum_e mglKey, U32 len, void *pValue);

/**
 * @brief        查询控制卡属性s
 * @param[in]    ctrlId : 控制卡标识符
 * @param[in]    keyName: 查询的字段名称
 * @param[in]    len    : 要查询的value长度
 * @param[out]   value  : 查询到的value
 * @return       PS3_ERRNO_SUCCESS: 成功, 其他: 失败
 */
Ps3Errno ps3libCtrlModuleCfgGet(CtrlId_t ctrlId, Ps3LibCfgKeyEnum_e mglKey, U32 len, void *pValue);

#if defined(__cplusplus)
}
#endif

#endif